baseURL = "http://example.org/"
languageCode = "ja"
title = "tact"
contentDir = "post"
disableKinds = ["RSS", "sitemap"]
theme ="hugo-theme-dream"
[taxonomies]
tag = "tags"


[params]
  background = "#731BC8"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "tact"
  # description = ""
  avatar = "/img/tact.jpg"
  motto = "20"
  # categoriesLimitInHeader = 6
  # headerBottomText = ""
  disqusShortname = "..."
  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "003starrysky@gmail.com"
  twitter = "@SoedaTakuto"
  facebook = "tactsoeda"
  instagram = "tact00369"
  # mastodon = ""
  # linkedin = ""
  github = "takutosoeda"
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2020

  favicon = "/top.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true
